<!-- Common Footer for all pages -->
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <div class="widget">
            <h3 class="widgetheading">Our Contact</h3>
            <address>
              <strong>SHASHWATI</strong> - Ano Rectal Hospital<br>
              201, Varna Building, Near Heena Garden<br>
              Behind University, Gandhari
              Kalyan West Pin-421301<br>
              Maharashtra, IN.
            </address>
            <p>
              <i class="icon-phone"></i> +91 77770 01480 <br>
              <i class="icon-phone"></i> +91 98907 72802 <br>
              <i class="icon-envelope-alt"></i> info@shashwatiinpiles.com
            </p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="widget">
            <h3 class="widgetheading">Consulting Hours</h3>
            <ul class="link-list">
              <li><a href="#">Morning: 10:00 am to 01:00 pm</a></li>
              <li><a href="#">Evening: 06:00 pm to 09:30 pm</a></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="widget">
            <h5 class="widgetheading">Location Map</h5>
              <style>#map {height:300px; width:100%; background-color:grey;}</style>
              <div id="map"></div>
              <!--ul class="link-list">
                <li><a href="#">Latest Events</a></li>
                <li><a href="#">Terms and conditions</a></li>
                <li><a href="#">Privacy policy</a></li>
                <li><a href="#">Career</a></li>
                <li><a href="#">Contact us</a></li>
              </ul-->
          </div>
        </div>
      </div>
    </div>
    <div id="sub-footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-9">
            <div class="copyright">
              Copyright &copy; <a href="http://www.shashwatiinpiles.com"><strong>SHASHWATI</strong> - Ano Rectal Hospital</a> 2010-2016 All right reserved.
              <ul class="social-network">
                <li><a href="#" data-placement="top" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#" data-placement="top" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#" data-placement="top" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="#" data-placement="top" title="Pinterest"><i class="fa fa-pinterest"></i></a></li>
                <li><a href="#" data-placement="top" title="Google plus"><i class="fa fa-google-plus"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3">
            <p><span class="pull-right">Maintained by: <a href="http://www.dgsol-in.com" target="_blank"><strong>DGSOL InfoTech</strong></a></span></p>
          </div>
        </div>
      </div>
    </div>
