	<header>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.php"><img src="img/logo.jpg" style="max-height:60px; margin-top: -7px;" alt="SHASHWATI"/></a>
        </div>
        <div class="navbar-collapse collapse ">
          <ul class="nav navbar-nav">
            <li class="active"><a href="index.php">Home</a></li> 
						<li><a href="about.php">About Us</a></li>
						<li><a href="facilities.php">Facilities</a></li>
            <li><a href="portfolio.php">Portfolio</a></li>
            <li><a href="contact.php">Contact</a></li>
            <li><a href="consultation.php">Consultation</a></li>
          </ul>
        </div>
      </div>
    </div>
	</header>
